[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
sol_adz = "EX7SaCEZcWqM8reppz6tXqXsnczP2MFXPBaaXYAYwLYR"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "anchor test"
